// --- Data Kuis ---
const quizData = [
    { question: "Tag HTML apa yang digunakan untuk membuat paragraf?",
        options: ["<p>", "<h1>", "<br>", "<hr>"],
        answer: "<p>" },
    { question: "Manakah properti CSS yang digunakan untuk mengubah warna teks?",
        options: ["font-color", "text-color", "color", "background-color"],
        answer: "color" },
    { question: "Elemen HTML manakah yang digunakan untuk membuat hyperlink?",
        options: ["<link>", "<a>", "<href>", "<url>"],
        answer: "<a>" },
    { question: "Bagaimana cara menyisipkan komentar di file CSS?",
        options: ["// ini komentar", "# ini komentar", "/* ini komentar */", "' ini komentar"],
        answer: "/* ini komentar */" },
    { question: "Atribut HTML manakah yang digunakan untuk mendefinisikan style inline?",
        options: ["class", "styles", "font", "style"],
        answer: "style" },
    { question: "Properti CSS manakah yang mengontrol ukuran teks?",
        options: ["font-style", "text-size", "font-size", "text-style"],
        answer: "font-size" },
    { question: "Apa kepanjangan dari HTML?",
        options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyperlink and Text Markup Language", "Home Tool Markup Language"], answer: "Hyper Text Markup Language" },
    { question: "Selector CSS manakah yang memilih elemen dengan id 'header'?",
        options: [".header", "#header", "header", "*header"],
        answer: "#header" },
    { question: "Tag HTML manakah yang digunakan untuk membuat daftar berurutan (ordered list)?",
        options: ["<ul>", "<li>", "<ol>", "<dl>"],
        answer: "<ol>" },
    { question: "Apa kepanjangan dari CSS?",
        options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"],
        answer: "Cascading Style Sheets" }
];